import Config

# Configure your database
config :backend, Backend.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "backend_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :backend, BackendWeb.Endpoint,
  # Bound to all interfaces so devices on the local network (e.g. a phone)
  # can reach it directly; Vite's dev proxy also forwards to it internally.
  http: [ip: {0, 0, 0, 0}],
  # false rather than an allowlist: an ngrok tunnel gets a fresh random
  # domain on every restart, so any fixed origin list would need editing
  # each time. Combined with the wildcard CORSPlug in endpoint.ex, requests
  # (WS and HTTP alike) are accepted from the ngrok domain with no changes.
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "R0wOjJUI+f2wf5Pgfb94PCodjtHfI+IpTQBLIBPFeqaOqIhezY4m6T6zdsmJTIt9",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :backend, dev_routes: true

# BackendWeb.RequireCloudflarePlug no-ops when :cloudflare_origin_secret is
# unset (the default here) — nothing sits in front of this app locally for
# there to be a Cloudflare hop to verify. To exercise the plug's rejection
# path locally (e.g. testing a Cloudflare Transform Rule setup end to end
# against this dev server), uncomment both lines below with matching
# values and send requests with a `X-Origin-Secret: dev-secret` header:
#
# config :backend, :cloudflare_origin_secret, "dev-secret"

# To test S3/R2 uploads locally instead of local-disk storage, fill in real
# credentials below (see config/runtime.exs for the production equivalent
# and Backend.Uploads.S3 for how the request is signed). Left as :local by
# default (config.exs) since no bucket/credentials are available in this
# dev environment.
#
# config :backend, :uploads,
#   adapter: :s3,
#   bucket: "zircle-uploads-dev",
#   region: "auto",
#   endpoint: "https://<account_id>.r2.cloudflarestorage.com",
#   access_key_id: "...",
#   secret_access_key: "...",
#   public_url_base: "https://pub-xxxxxxxx.r2.dev"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
